Repository ch3nkula/awmd-stats, pull requests merged in 2018-03, with the labels that each got.

#9 Fix Flask bug with protocol inconsistency
  app.py
  static/js/main.js
  templates/base.html
  templates/index.html
  templates/submitter.html
Labels: enhancement

#17 Refresh page when the refresh icon is clicked
  static/js/main.js
  templates/base.html
Labels: bug, enhancement

#18 Add JavaScript hard refresh on pages
  static/js/main.js
Labels: enhancement

#19 Adding color marks to install-dep.sh script
  install-deps.sh
Labels: enhancement

#20 Minor refactoring, changed 'submitter' to 'contributor'
  app.py
  install-deps.sh
Labels: enhancement

#22 Minor fix
  templates/base.html
Labels: enhancement

#23 Fixing links and issues in the app, refactoring a little
  app.py
  templates/base.html
  templates/contributor.html
  templates/stats.html
Labels: enhancement, refactoring

#24 Automated unit tests for the app
  .gitignore
  app.py
  db/db.json
  test_app.py
Labels: enhancement, help wanted
